#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from koala import classe
import optparse
from subprocess import Popen, PIPE
import zipfile
import gzip
import cProfile
import shutil

os.environ["GMX_MAXBACKUP"] = "-1"


class CheckPDBStructure(object):
    """
    Check PDB structure according to GROMACS.
    This scripts uses the pdb2gmx to verify the PDB files.
    """
    path_execute = None
    check_pdb_log = 'check-pdb-log.txt'

    def __init__(self, opts=None):
        """
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        @type opts: OptionParser parameters
        """
        assert opts is not None
        self.opts = opts
        self.ClassColection = classe.IcmcGalaxy()

    def delete_check_files(self):
        """
        Delete the temporary files generated by GROMACS
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        """
        try:
            if os.path.isfile(os.path.join(self.path_execute, 'check.top')):
                os.remove(os.path.join(self.path_execute, 'check.top'))
            if os.path.isfile(os.path.join(self.path_execute, 'check.gro')):
                os.remove(os.path.join(self.path_execute, 'check.gro'))
            if os.path.isfile(os.path.join(self.path_execute, 'posre.itp')):
                os.remove(os.path.join(self.path_execute, 'posre.itp'))
        except Exception, e:
            self.ClassColection.ShowErrorMessage(str(e))

    def log_by_pdb2gmx(self, pdbfile, stderr=None, stdout=None):
        """
        Write the log file with the stderr from pdb2gmx
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        @type pdbfile: file
        @type stderr: string
        @type stdout: string
        """
        try:
            f_log = open(os.path.join(self.path_execute, self.check_pdb_log), "a+")
            pdbfile = os.path.split(pdbfile)[1]
            outline = "STARTING LOG OF " + pdbfile + "\n"
            f_log.write(outline)
            outline = stderr + "\n"
            f_log.write(outline)
            outline = "FINISHED LOG OF " + pdbfile + "\n\n\n"
            f_log.write(outline)
            f_log.close()
        except Exception, e:
            self.ClassColection.ShowErrorMessage(str(e))

    def moveStructures(self, pdbfile):
        """
        Move a PDB file to a specific directory
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        @type pdbfile: file
        """
        try:
            directory = os.path.join(self.path_execute, 'no_accepted_by_pdb2gmx')
            if(not os.path.exists(directory)):
                os.makedirs(directory)
            shutil.move(pdbfile, directory)
        except Exception, e:
            self.ClassColection.ShowErrorMessage(str(e))

    def check_structue_by_pdb2gmx(self, pdbfile, gmx_path, forcefield):
        """
        Create a subprocess to verify all the PDB input files
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        @type pdbfile: file
        @type gmx_path: string
        @type forcefield: string
        """
        try:
            self.delete_check_files()

            program = os.path.join(gmx_path, "pdb2gmx")

            process = Popen([
                    program,
                    '-f',
                    pdbfile,
                    '-o',
                    'check.gro',
                    '-p',
                    'check.top',
                    '-water',
                    'none',
                    '-ff',
                    forcefield,
                    '-ignh'], stdout=PIPE, stderr=PIPE)

            stdout, stderr = process.communicate()
            process.wait()

            # Checking output of pdb2gmx of pdbfile
            if stderr.find('Fatal error') >= 0:
                self.log_by_pdb2gmx(pdbfile, stderr)
                self.moveStructures(pdbfile)

            self.delete_check_files()

        except Exception, e:
            self.ClassColection.ShowErrorMessage(str(e))

    def run_CheckPDBStructure(self):
        """
        Get the PDB files and run the checking
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        """
        try:
            dir_execucao = self.ClassColection.CreateExecutionDirectory()
            self.path_execute = self.ClassColection.getPathExecute() + dir_execucao

            if self.opts.compressedFile == '1':

                inputFiles = self.opts.inputPDBs.split(",")

                for input_f in inputFiles:
                    if zipfile.is_zipfile(input_f):
                        self.ClassColection.extractZipFile(input_f, self.path_execute)
                    else:
                        try:
                            inF = gzip.GzipFile(input_f, 'rb')
                            f = inF.read()
                            inF.close()
                            if f:
                                self.ClassColection.extractGzFile(input_f, self.path_execute)
                        except Exception, e:
                            raise Exception("The input file could not be read.\n%s" % e)
            else:
                    self.ClassColection.copyPDBsFromInput(
                        self.path_execute,
                        self.opts.outputdir,
                        self.opts.inputnames,
                        self.opts.inputPDBs)

            pdbs = self.ClassColection.listDirectory(self.path_execute, "*.pdb")

            for pdb in pdbs:
                self.check_structue_by_pdb2gmx(
                        os.path.join(self.path_execute, pdb),
                        self.ClassColection.getPathGromacs(),
                        self.opts.forceField)

            path_output, file_output = os.path.split(self.opts.output)

            pdbs_accepted = self.ClassColection.listDirectory(self.path_execute, "*.pdb")

            if self.ClassColection.compressFiles(pdbs_accepted, self.path_execute, "PDBsChecked"):
                self.ClassColection.sendOutputResults(
                        path_output,
                        file_output,
                        os.path.join(self.path_execute, 'PDBsChecked.zip'))

            if(os.path.exists(os.path.join(self.path_execute, self.check_pdb_log))):
                self.ClassColection.sendMultipleOutputs(
                        path_output,
                        [os.path.join(self.path_execute, self.check_pdb_log)],
                        self.opts.galaxydir,
                        self.opts.outputID)

        except Exception, e:
            self.ClassColection.ShowErrorMessage(str(e))

if __name__ == '__main__':
    op = optparse.OptionParser()
    op.add_option('-i', '--inputPDBs', default=None)
    op.add_option('-f', '--forceField', default='amber99sb-ildn')
    op.add_option('-n', '--inputnames', default=None)
    op.add_option('-o', '--output', default=None)
    op.add_option('-d', '--outputdir', default=None)
    op.add_option('-r', '--galaxyroot', default=None)
    op.add_option('-s', '--compressedFile', default=None)
    op.add_option('-t', '--toolname', default=None)
    op.add_option('-c', '--outputID', default=None)
    op.add_option('-g', '--galaxydir', default=None)
    opts, args = op.parse_args()

    if not os.path.exists(opts.outputdir):
        os.makedirs(opts.outputdir)

    checkpdb = CheckPDBStructure(opts)

    cProfile.run('checkpdb.run_CheckPDBStructure()', 'profileout.txt')

    checkpdb.ClassColection.clearPathExecute(checkpdb.path_execute)
