#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import classe
import optparse
from subprocess import Popen, PIPE
import cProfile


class RenameAtoms(object):
    """
    Rename the missing atoms of a PDB file according to GROMACS
    """

    path_execute = None
    os.environ["GMX_MAXBACKUP"] = "-1"

    def __init__(self, opts=None):
        """
        @type self: koala.RenameAtoms.RenameAtoms
        @type opts: OptionParser parameters
        """
        assert opts is not None
        self.opts = opts
        self.ClassColection = classe.IcmcGalaxy()

    def delete_check_files(self):
        """
        Delete the temporary files generated by GROMACS
        @type self: koala.RenameAtoms.RenameAtoms
        """
        if os.path.isfile(os.path.join(self.path_execute, 'check.top')):
            os.remove(os.path.join(self.path_execute, 'check.top'))
        if os.path.isfile(os.path.join(self.path_execute, 'posre.itp')):
            os.remove(os.path.join(self.path_execute, 'posre.itp'))

    def rename_atoms_structure(self, pdbfile, gmx_path, forcefield):
        """
        Create a subprocess to rename the atoms of the PDB input file using pdb2gmx
        @type self: koala.RenameAtoms.RenameAtoms
        @type pdbfile: file
        @type gmx_path: string
        @type forcefield: string
        """
        self.delete_check_files()
        program = os.path.join(gmx_path, "pdb2gmx")
        process = Popen([
                program,
                '-f',
                pdbfile,
                '-o',
                pdbfile,
                '-p',
                'check.top',
                '-water',
                'none',
                '-ff',
                forcefield], stdout=PIPE, stderr=PIPE)
        stdout, stderr = process.communicate()
        process.wait()
        self.delete_check_files()

    def run_RenameAtoms(self):
        """
        Get the PDB file and run the renaming
        @type self: koala.CheckPDBStructure.CheckPDBStructure
        """
        try:
            dir_execucao = self.ClassColection.CreateExecutionDirectory()
            new_path = self.ClassColection.getPathExecute() + dir_execucao
            self.path_execute = new_path

            self.opts.pdbName = self.opts.pdbName.replace(
                ' ', '-').replace('(', '').replace(')', '')

            link_name = os.path.join(self.opts.outputdir, os.path.basename(self.opts.pdbName))
            if not os.path.exists(link_name):
                os.symlink(self.opts.inputPDB, link_name)
                os.system("cp %s %s" % (link_name, self.path_execute))

            self.rename_atoms_structure(
                    os.path.join(self.path_execute, self.opts.pdbName),
                    self.ClassColection.getPathGromacs(),
                    self.opts.forceField
            )

            path_output, file_output = os.path.split(self.opts.output)

            self.ClassColection.sendOutputResults(
                    path_output,
                    file_output,
                    os.path.join(self.path_execute, self.opts.pdbName))

        except Exception, e:
            self.ClassColection.ShowErrorMessage(str(e))

if __name__ == '__main__':
    op = optparse.OptionParser()
    op.add_option('-i', '--inputPDB', default=None)
    op.add_option('-f', '--forceField', default='amber99sb-ildn')
    op.add_option('-n', '--pdbName', default=None)
    op.add_option('-o', '--output', default=None)
    op.add_option('-d', '--outputdir', default=None)
    op.add_option('-r', '--galaxyroot', default=None)

    opts, args = op.parse_args()
    if not os.path.exists(opts.outputdir):
        os.makedirs(opts.outputdir)

    rnatoms = RenameAtoms(opts)

    cProfile.run('rnatoms.run_RenameAtoms()', 'profileout.txt')

    rnatoms.ClassColection.clearPathExecute(rnatoms.path_execute)
